resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: github                       # <-- replace with your integration
      path: hshanka/jfrog-pipelines-docker-sample    # <-- replace with your repository name
      branches:
        include: master

  - name: dbp_image
    type: Image
    configuration:
      registry: hshanka_artifactory_integration                                # <-- replace with your artifactory integration
      sourceRepository: hshanka/jfrogexample               # <-- required if registry is Artifactory
      imageName: hshanka.jfrog.io/hshanka-docker-docker/jfrog-docker-example-image  # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: dbp_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: hshanka_artifactory_integration
      buildName: dbp_build
      buildNumber: 1    

  - name: dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: hshanka_artifactory_integration
      buildName: dbp_build
      buildNumber: 1
      
  - name: cron_trigger_docker
    type: CronTrigger
    configuration:
      interval: '0 2 * * *'       
      

pipelines:
  - name: Docker_Quickstart
    configuration:
      jfrogCliVersion: 2  
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: hshanka.jfrog.io/hshanka-docker-docker/jfrog-docker-example-image  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo
            - name: cron_trigger_docker
          integrations:
            - name: hshanka_artifactory_integration                            # <-- replace with your artifactory integration
        execution:
          onStart:
              # - msg="Run description updated from step $step_id"
              # - update_run_description "$msg"  
              - update_run_description "Add custom text for every run. Example - Build and push Docker image to Artifactory."

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: quickstarts-target-local
          integrations:
            - name: hshanka_artifactory_integration                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image           

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build_info          

      - name: bash_builds
        type: Bash
        configuration:
          integrations:
            - name: hshanka_artifactory_integration
          inputSteps:
            - name: docker_build
        execution:
          onExecute:
            - touch test.txt
            - echo "Hello World" > test.txt
            - cat test.txt
            # - save_artifact_info 'file' './test.txt'
            - save_artifact_info file test.txt
            - save_artifact_info 'buildInfo' './test.txt' --build-name bash_builds_test --build-number ${run_number}

      - name: promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: quickstarts-target-local
          integrations:
            - name: hshanka_artifactory_integration
          inputResources:
            - name: dbp_build_info
          outputResources:
            - name: dbp_promoted_build_info
